[workspace]

resolver = "2"
members = [
    "db-desktop",
    "src-tauri",
]

[workspace.package]
version = "0.1.0-dev.1"
edition = "2021"
authors = ["Charles Dong <chardon_cs@proton.me>"]
license = "MIT"
repository = "https://github.com/chardoncs/ollama-lab.git"
rust-version = "1.80"
