"$schema" = "../gen/schemas/desktop-schema.json"

identifier = "default"
windows = ["main"]
permissions = [
    "core:app:default",
    "core:event:default",
    "core:menu:default",
    "core:path:default",
    "core:window:default",
]
