<script lang="ts">
  import type { ModelEntry, ModelInfo } from "$lib/models/models"
  import { CodeBlock, popup, Tab, TabGroup } from "@skeletonlabs/skeleton";
  import { IconCloudUpload, IconDotsVertical, IconPointFilled, IconTrash } from "@tabler/icons-svelte";
  import convert from "convert";
  import TimeAgo from "javascript-time-ago"
  import en from 'javascript-time-ago/locale/en'

  TimeAgo.addDefaultLocale(en)

  const timeAgo = new TimeAgo("en-US")

  export let entry: ModelEntry

  let modelInfo: ModelInfo = {
    "modelfile": "# Modelfile generated by \"ollama show\"\n# To build a new Modelfile based on this one, replace the FROM line with:\n# FROM llava:latest\n\nFROM /Users/matt/.ollama/models/blobs/sha256:200765e1283640ffbd013184bf496e261032fa75b99498a9613be4e94d63ad52\nTEMPLATE \"\"\"{{ .System }}\nUSER: {{ .Prompt }}\nASSISTANT: \"\"\"\nPARAMETER num_ctx 4096\nPARAMETER stop \"\u003c/s\u003e\"\nPARAMETER stop \"USER:\"\nPARAMETER stop \"ASSISTANT:\"",
    "parameters": "num_keep                       24\nstop                           \"<|start_header_id|>\"\nstop                           \"<|end_header_id|>\"\nstop                           \"<|eot_id|>\"",
    "template": "{{ if .System }}<|start_header_id|>system<|end_header_id|>\n\n{{ .System }}<|eot_id|>{{ end }}{{ if .Prompt }}<|start_header_id|>user<|end_header_id|>\n\n{{ .Prompt }}<|eot_id|>{{ end }}<|start_header_id|>assistant<|end_header_id|>\n\n{{ .Response }}<|eot_id|>",
    "details": {
      "parent_model": "",
      "format": "gguf",
      "family": "llama",
      "families": [
        "llama"
      ],
      "parameter_size": "8.0B",
      "quantization_level": "Q4_0"
    },
    "model_info": {
      "general.architecture": "llama",
      "general.file_type": 2,
      "general.parameter_count": 8030261248,
      "general.quantization_version": 2,
      "llama.attention.head_count": 32,
      "llama.attention.head_count_kv": 8,
      "llama.attention.layer_norm_rms_epsilon": 0.00001,
      "llama.block_count": 32,
      "llama.context_length": 8192,
      "llama.embedding_length": 4096,
      "llama.feed_forward_length": 14336,
      "llama.rope.dimension_count": 128,
      "llama.rope.freq_base": 500000,
      "llama.vocab_size": 128256,
      "tokenizer.ggml.bos_token_id": 128000,
      "tokenizer.ggml.eos_token_id": 128009,
      "tokenizer.ggml.merges": [],            // populates if `verbose=true`
      "tokenizer.ggml.model": "gpt2",
      "tokenizer.ggml.pre": "llama-bpe",
      "tokenizer.ggml.token_type": [],        // populates if `verbose=true`
      "tokenizer.ggml.tokens": []             // populates if `verbose=true`
    }
  }

  let tabs: { value: string, label: string }[] = [
    { value: "details", label: "Details" },
    { value: "info", label: "Model info" },
    { value: "modelfile", label: "Modelfile" },
    { value: "params", label: "Parameters" },
    { value: "template", label: "Template" },
  ]

  let currentTab: string = "details"
</script>

<div class="w-full h-dvh flex flex-col">
  <div class="flex flex-col px-4 py-2 lg:px-8 lg:py-6 overflow-y-scroll">
    <div class="flex flex-col md:px-6 md:py-8 lg:px-12 lg:py-14 gap-5">
      <div class="flex-auto flex">
        <h1 class="font-bold text-2xl flex-auto">{entry.name}</h1>
        <div class="flex place-items-center">
          <button class="btn-icon btn-icon-sm variant-ghost" use:popup={{
            event: "click",
            target: "popupOps",
            placement: "bottom-end",
          }}>
            <IconDotsVertical />
          </button>
          <div class="card" data-popup="popupOps">
            <ul class="list">
              <li>
                <button class="btn rounded-none flex place-content-center">
                  <IconCloudUpload />
                  <span>Push</span>
                </button>
              </li>
              <li>
                <button class="btn rounded-none flex place-content-center">
                  <IconTrash class="text-error-600 dark:text-error-400" />
                  <span>Delete</span>
                </button>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="flex gap-3">
        {#if entry.status}
          <div class="flex gap-1 place-items-center">
            <IconPointFilled class="text-green-600 dark:text-green-400" />
            <span>Running</span>
          </div>
          <div class="flex gap-4">
            <span title={entry.size.toLocaleString() + " bytes"}>
              VRAM: {convert(entry.status.size_vram, "byte").to("best", "imperial").toString(2)}
            </span>
            <span title={entry.status.expires_at.toString()}>
              Session expires {timeAgo.format(entry.status.expires_at)}
            </span>
          </div>
        {:else}
          <div class="flex gap-1 place-items-center">
            <IconPointFilled class="text-gray-600 dark:text-gray-400" />
            <span>Inactive</span>
          </div>
        {/if}
      </div>
    </div>
    <div class="flex flex-col card px-3 py-2">
      <TabGroup>
        {#each tabs as { value, label } (value)}
          <Tab bind:group={currentTab} name="{value}Tab" {value}>{label}</Tab>
        {/each}

        <svelte:fragment slot="panel">
          <div class="flex flex-col gap-1 px-3 py-4">
            {#if currentTab === "details"}
              <span>Model family: {modelInfo.details.family}</span>
              <span>Parent model: {modelInfo.details.parent_model || "(none)"}</span>
              <span>Parameter size: {modelInfo.details.parameter_size}</span>
              <span>Format: {modelInfo.details.format}</span>
              <span>Model size: {convert(entry.size, "byte").to("best", "imperial").toString(2)} ({entry.size.toLocaleString()} bytes)</span>
              <span>Quantization Level: {modelInfo.details.quantization_level}</span>
            {:else if currentTab === "info"}
              <div class="table-container">
                <table class="table table-hover">
                  {#each Object.entries(modelInfo.model_info) as [key, value] (key)}
                    <tr class="border-b border-surface-400 dark:border-surface-700">
                      <td>{key}</td>
                      <td>{value.toString()}</td>
                    </tr>
                  {/each}
                </table>
              </div>
            {:else if currentTab === "modelfile"}
              <CodeBlock language="modelfile" code={modelInfo.modelfile} buttonCopied="Copied" />
            {:else if currentTab === "params"}
              <CodeBlock code={modelInfo.parameters} buttonCopied="Copied" />
            {:else if currentTab === "template"}
              <CodeBlock code={modelInfo.template} buttonCopied="Copied" />
            {/if}
          </div>
        </svelte:fragment>
      </TabGroup>
    </div>
  </div>
</div>
